name: locorda_init_generator
description: Code generator for Locorda convenience wrapper (initLocorda)
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  # CRITICAL: Must support range from stable Flutter (8.4.x) to latest (10.x)
  # See: https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/lib/src/web/compile.dart
  analyzer: '>=8.1.0 <11.0.0'
  build: ^4.0.4
  dart_style: ">=2.3.7 <4.0.0"
  glob: ^2.1.2
  logging: ^1.2.0
  locorda_core: any
  locorda_rdf_core: any
  path: ^1.9.1
  source_gen: ^4.2.0
  locorda_rdf_terms_core: ^0.11.9
  

dev_dependencies:
  test: ^1.26.3
  build_runner: ^2.11.1
  build_test: ^3.5.7
  
