// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
//
// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field
// ignore_for_file: depend_on_referenced_packages

import 'package:locorda_rdf_mapper/mapper.dart';

import 'package:minimal_task_sync/task.dart' as task;
import 'package:minimal_task_sync/task.rdf_mapper.g.dart' as trmg;
import 'package:locorda_core/locorda_core.dart' as locorda_core;

/// Initializes and returns an RdfMapper with mappers registered.
///
/// [rdfMapper] An optional RdfMapper instance to use. If not provided, a new one will be created.
/// * [$resourceIriFactory]
RdfMapper initRdfMapper({
  RdfMapper? rdfMapper,
  required IriTermMapper<(String id,)> Function<T>(locorda_core.RootIriConfig)
      $resourceIriFactory,
}) {
  if (rdfMapper == null) {
    rdfMapper = RdfMapper.withDefaultRegistry();
  }
  var registry = rdfMapper.registry;

  registry.registerMapper<task.Task>(
    trmg.TaskMapper(
      iriMapper: $resourceIriFactory<task.Task>(
        const locorda_core.RootIriConfig('it'),
      ),
    ),
  );

  return rdfMapper;
}
