// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: lib/task.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field, unnecessary_string_interpolations

import 'package:locorda_rdf_core/core.dart';
import 'package:locorda_rdf_mapper/mapper.dart';

// Other imports
import 'package:minimal_task_sync/task.dart' as task;
import 'package:locorda_rdf_terms_schema/schema.dart';
import 'package:locorda_core/locorda_core.dart' as locorda_core;

/// Generated mapper for [task.Task] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `task.Task`.
class TaskMapper implements GlobalResourceMapper<task.Task> {
  final IriTermMapper<(String id,)> _iriMapper;

  /// Constructor
  const TaskMapper({required IriTermMapper<(String id,)> iriMapper})
    : _iriMapper = iriMapper;

  @override
  IriTerm? get typeIri =>
      const IriTerm('https://locorda.dev/example/minimal/Task');

  @override
  task.Task fromRdfResource(IriTerm subject, DeserializationContext context) {
    final reader = context.reader(subject);

    final (id,) = _iriMapper.fromRdfTerm(subject, context);

    final String title = reader.require(SchemaThing.name);
    final bool completed = reader.require(
      const IriTerm('https://locorda.dev/example/minimal#completed'),
    );
    final DateTime createdAt = reader.require(SchemaCreativeWork.dateCreated);

    return task.Task(
      id: id,
      title: title,
      completed: completed,
      createdAt: createdAt,
    );
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    task.Task resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = _iriMapper.toRdfTerm((resource.id,), context);

    return context
        .resourceBuilder(subject)
        .addValue(SchemaThing.name, resource.title)
        .addValue(
          const IriTerm('https://locorda.dev/example/minimal#completed'),
          resource.completed,
        )
        .addValue(SchemaCreativeWork.dateCreated, resource.createdAt)
        .build();
  }
}
