name: locorda_objects
description: Locorda Objects - Sync offline-first apps using your user's remote storage
version: 0.5.0
publisher: locorda.dev
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  locorda_core: ^0.5.0
  
  # RDF mapping
  locorda_rdf_core: ^0.12.2
  locorda_rdf_mapper: ^0.12.2

dev_dependencies:
  test: ^1.26.3

topics:
  - rdf
  - crdt
  - solid
  - offline-first
  - sync