name: locorda_objects
description: Locorda Objects - Sync offline-first apps using your user's remote storage
version: 0.1.0-dev
publish_to: none
publisher: locorda.dev
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  locorda_core: any
  
  # RDF mapping
  locorda_rdf_core: ^0.11.7
  locorda_rdf_mapper: ^0.11.7

dev_dependencies:
  test: ^1.26.3

topics:
  - rdf
  - crdt
  - solid
  - offline-first
  - sync