name: locorda_solid_auth
description: Locorda Solid Auth - Solid authentication implementation for locorda using solid-auth
version: 0.1.0-dev
homepage: https://locorda.dev/
repository: https://github.com/locorda/locorda
issue_tracker: https://github.com/locorda/locorda/issues
publish_to: none
publisher: locorda.dev
resolution: workspace

topics:
  - solid
  - authentication
  - oidc

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  logging: ^1.3.0
  locorda_core: any
  locorda_solid_core: any
  locorda_ui: any
  url_launcher: ^6.3.1

  # Solid authentication
  solid_oidc_auth: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ">=5.1.1 <7.0.0"

flutter:
  generate: true
