name: locorda_annotations
description: Locorda Annotations - CRDT merge strategy annotations for code generation
version: 0.1.0-dev
publisher: locorda.dev
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  locorda_rdf_mapper_annotations: ^0.12.2
  locorda_core: any

dev_dependencies:
  test: ^1.26.3

topics:
  - rdf
  - crdt
  - solid
  - annotations
  - codegen