// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: lib/models/category_display_settings.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field, unnecessary_string_interpolations
// ignore_for_file: depend_on_referenced_packages

import 'package:locorda_rdf_core/core.dart';
import 'package:locorda_rdf_mapper/mapper.dart';

// Other imports
import 'package:personal_notes_app/models/category_display_settings.dart'
    as cds;

/// Generated mapper for [cds.CategoryDisplaySettings] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `cds.CategoryDisplaySettings`.
class CategoryDisplaySettingsMapper
    implements LocalResourceMapper<cds.CategoryDisplaySettings> {
  /// Constructor
  const CategoryDisplaySettingsMapper();

  @override
  IriTerm? get typeIri => const IriTerm(
        'https://locorda.dev/example/personal_notes_app/vocabulary/personal-notes#CategoryDisplaySettings',
      );

  @override
  cds.CategoryDisplaySettings fromRdfResource(
    BlankNodeTerm subject,
    DeserializationContext context,
  ) {
    final reader = context.reader(subject);

    final String? color = reader.optional(
      const IriTerm(
        'https://locorda.dev/example/personal_notes_app/vocabulary/personal-notes#categoryColor',
      ),
    );
    final String? icon = reader.optional(
      const IriTerm(
        'https://locorda.dev/example/personal_notes_app/vocabulary/personal-notes#categoryIcon',
      ),
    );

    return cds.CategoryDisplaySettings(color: color, icon: icon);
  }

  @override
  (BlankNodeTerm, Iterable<Triple>) toRdfResource(
    cds.CategoryDisplaySettings resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = BlankNodeTerm();

    return context
        .resourceBuilder(subject)
        .when(
          resource.color != null,
          (b) => b.addValue(
            const IriTerm(
              'https://locorda.dev/example/personal_notes_app/vocabulary/personal-notes#categoryColor',
            ),
            resource.color,
          ),
        )
        .when(
          resource.icon != null,
          (b) => b.addValue(
            const IriTerm(
              'https://locorda.dev/example/personal_notes_app/vocabulary/personal-notes#categoryIcon',
            ),
            resource.icon,
          ),
        )
        .build();
  }
}
